In [1]:
import numpy as np

In [2]:
A = np.array([[1,0],
             [1,3]])
A

array([[1, 0],
       [1, 3]])

In [3]:
np.diag(A)

array([1, 3])

In [5]:
np.diag(np.diag(A))

array([[1, 0],
       [0, 3]])

In [11]:
e_vals, e_vecs = np.linalg.eig(A)
e_vecs.shape

(2, 2)

In [14]:
D = np.diag(e_vals)
D

array([[3., 0.],
       [0., 1.]])

In [18]:
Q = e_vecs
Q

array([[ 0.        ,  0.89442719],
       [ 1.        , -0.4472136 ]])

In [19]:
Q@D@np.linalg.inv(Q)

array([[1., 0.],
       [1., 3.]])

In [20]:
A@Q[:,0]

array([0., 3.])

In [22]:
Q[:,0]*e_vals[0]

array([0., 3.])

In [25]:
A@Q[:,1]

array([ 0.89442719, -0.4472136 ])

In [23]:
Q[:,1]*e_vals[1]

array([ 0.89442719, -0.4472136 ])