In [2]:
import numpy as np
import random

In [13]:
# BINARY REPRESENTATIONS
for i in range(5):
    b = random.getrandbits(4)
    print(b, bin(b), bin(b)[2:]) #  converts a specified integer number to its binary

14 0b1110 1110
10 0b1010 1010
3 0b11 11
9 0b1001 1001
11 0b1011 1011


In [14]:
random.random()

0.39773188161757256

In [37]:
numbers = np.arange(10)
random.choice(numbers) # Sample from given list

2

In [36]:
random.uniform(5, 10) # Sample from uniform distribution

9.662669177242654

In [157]:
np.random.seed(42)

x1 = np.random.rand(5)
x2 = np.random.rand(5)

print(x1.shape)
print(type(x1))
print(x1)
print('')
print(x2.shape)
print(type(x2))
print(x2)


X = np.array([x2,x2]).T

(5,)
<class 'numpy.ndarray'>
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

(5,)
<class 'numpy.ndarray'>
[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]


In [158]:
print(X.shape)
X

(5, 2)


array([[0.15599452, 0.15599452],
       [0.05808361, 0.05808361],
       [0.86617615, 0.86617615],
       [0.60111501, 0.60111501],
       [0.70807258, 0.70807258]])

In [155]:
print(np.cov(X.T).shape)
np.cov(X.T)

(3, 3)


array([[ 0.09532548, -0.03144214,  0.09532548],
       [-0.03144214,  0.12469716, -0.03144214],
       [ 0.09532548, -0.03144214,  0.09532548]])

### ddof=True

In [148]:
print(f'COV(X1, X2):\n {np.cov(X[:,0], X[:,1])}\n') # Delta Degree of Freedom = True
print(f'var(X1): {np.var(e1, ddof=True)}')
print(f'var(X2): {np.var(e2, ddof=True)}')

COV(X1, X2):
 [[ 0.09532548 -0.03144214]
 [-0.03144214  0.12469716]]

var(X1): 0.09532548164256274
var(X2): 0.12469716417996111


### ddof=False

In [149]:
print(f'COV(X1, X2):\n {np.cov(X[:,0], X[:,1], ddof=False)}\n') # Delta Degree of Freedom = False
print(f'var(X1): {np.var(e1)}')
print(f'var(X2): {np.var(e2)}')

COV(X1, X2):
 [[ 0.07626039 -0.02515371]
 [-0.02515371  0.09975773]]

var(X1): 0.07626038531405019
var(X2): 0.0997577313439689
